[PHP]
expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL
zend.exception_ignore_args = On
variables_order = "EGPCS"
request_order = "GP"
memory_limit = 256M
max_execution_time = 30
file_uploads = On
upload_max_filesize = 5M
post_max_size = 8M
allow_url_include = Off
zend.assertions = -1
